version: "3.9"
    
services:
  nginx_prod:
    image: nginx:latest
    volumes:
      - ./project/prod/ng_data:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "8000:80" #ovo ne moram sad stavljati tu
    
  db_prod:
    image: mysql:5.7
    volumes:
      - ./project/prod/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress_prod:
    depends_on:
      - db_prod
    image: wordpress:latest
    volumes:
      - ./project/prod/wordpress_data/html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_prod:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
